%YAML:1.0

# Project 11.1之前的数据
project_name: "lvi_sam" 

#common parameters
imu_topic: "/camera/imu"
image_topic: "/zedm/zed_node/left/image_rect_color"
point_cloud_topic: "lvi_sam/lidar/deskew/cloud_deskewed"

# Lidar Params
use_lidar: 1                     # whether use depth info from lidar or not
lidar_skip: 3                    # skip this amount of scans
align_camera_lidar_estimation: 1 # align camera and lidar estimation for visualization

# lidar to camera extrinsic
lidar_to_cam_tx: 0.022
lidar_to_cam_ty: -0.054
lidar_to_cam_tz: -0.088
lidar_to_cam_rx:   1.5708  # roll
lidar_to_cam_ry: -1.5708  # pitch
lidar_to_cam_rz:  0.0   # yaw
# lidar to imu extrinsic 
lidar_to_imu_tx: -0.03
lidar_to_imu_ty: 0.442
lidar_to_imu_tz: -0.364
lidar_to_imu_rx: -1.5708
lidar_to_imu_ry: 1.5708
lidar_to_imu_rz: 0.0
# camera model
model_type: PINHOLE
camera_name: camera

image_width: 1280
image_height: 720
distortion_parameters:
   k1: 0.02672217
   k2: 0.0406309
   p1: -0.0049206
   p2: 0.0258076
projection_parameters:
   fx: 711.23351304823734
   fy: 716.23659796034985
   cx: 617.09872334638089
   cy: 382.00845599324589


#imu parameters       The more accurate parameters you provide, the worse performance
acc_n: 1.8278764625497403e-02         # accelerometer measurement noise standard deviation.
gyr_n: 2.2484739538368025e-03         # gyroscope measurement noise standard deviation.
acc_w: 6.7504987254087304e-04        # accelerometer bias random work noise standard deviation.
gyr_w: 3.5602903646558489e-05       # gyroscope bias random work noise standard deviation.
g_norm: 9.81007       # gravity magnitude
imu_hz: 200         # frequency of imu

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Don't know anything about extrinsic parameters. You don't need to give R,T. We will try to calibrate it. Do some rotation movement at beginning. 
#Rotation from camera frame to imu frame, imu^R_cam
extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 1,0.003922,-0.00825459,
           -0.00388915, -0.99998447,0.00399195, 
           0.00827012, -0.00395968, -0.99995796]
#Translation from camera frame to imu frame, imu^T_cam
extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [-0.052, 0.388, -0.452]

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 20            # min distance between two features 
freq: 20                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
equalize: 1             # if image is too dark or light, trun on equalize to find enough features
fisheye: 0              # if using fisheye, trun on it. A circle mask will be loaded to remove edge noisy points

#optimization parameters
max_solver_time: 0.035   # max solver itration time (ms), to guarantee real time
max_num_iterations: 10   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0  # keyframe selection threshold (pixel)

#unsynchronization parameters
estimate_td: 0           # online estimate time offset between camera and imu
td: -0.004492987156480011                   # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#rolling shutter parameters
rolling_shutter: 0       # 0: global shutter camera, 1: rolling shutter camera
rolling_shutter_tr: 0    # unit: s. rolling shutter read out time per frame (from data sheet). 

#loop closure parameters
loop_closure: 1                    # start loop closure
skip_time: 0.0
skip_dist: 0.0
debug_image: 0                      # save raw image in loop detector for visualization prupose; you can close this function by setting 0 
match_image_scale: 0.5
vocabulary_file: "/config/brief_k10L6.bin"
brief_pattern_file: "/config/brief_pattern.yml"
